// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pirmais_praktiskais_darbs.Models;

#nullable disable

namespace pirmais_praktiskais_darbs.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Amats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nosaukums")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amati");
                });

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Darbinieks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmatsId")
                        .HasColumnType("int");

                    b.Property<int>("DepartamentsId")
                        .HasColumnType("int");

                    b.Property<string>("Uzvards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AmatsId");

                    b.HasIndex("DepartamentsId");

                    b.ToTable("Darbinieki");
                });

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Departaments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nosaukums")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamenti");
                });

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Darbinieks", b =>
                {
                    b.HasOne("pirmais_praktiskais_darbs.Models.Amats", "Amats")
                        .WithMany("Darbinieki")
                        .HasForeignKey("AmatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pirmais_praktiskais_darbs.Models.Departaments", "Departaments")
                        .WithMany("Darbinieki")
                        .HasForeignKey("DepartamentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amats");

                    b.Navigation("Departaments");
                });

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Amats", b =>
                {
                    b.Navigation("Darbinieki");
                });

            modelBuilder.Entity("pirmais_praktiskais_darbs.Models.Departaments", b =>
                {
                    b.Navigation("Darbinieki");
                });
#pragma warning restore 612, 618
        }
    }
}
